### ISSUE TITLE
No more sentences to validate in kabyle (kab) locale

### ISSUE THREAD

**Issue by SelyanKab** [common-voice/common-voice#2781]
Hi,
since few days, Kabyle community is no longer being able to listen/validate sentences.
The listening section is not showing any content even if new records are being made every Day by community membres.
Kabyle at present has 547 hours recorded and 518 hours validated so this message should not be valid.
Could you check this out, please? Thanks.

**Comment by mozillakab** [comment]
After about a week (blocking on the sentence validation for the kab locale), I'm afraid that we we have to  redeploy the same effort to mobilize and recruit again contributors. If the issue persists it will be even harder to bring back contributors.

**Comment by YazidIflis** [comment]
Hi,
Any news on this subject?
Community members ask every day what is going on ... We fear that it will have an impact on their motivation without any explanation or feedback on the problem they are facing.
This affects all Kabyle contributors.
Do you need any additional inputs ? 
Kr
Yazid

**Comment by mozillakab** [comment]
@nukeador I think it's the same issue as #2746 

I'm using Firefox 77 on windows 7. With some addons User-Agent Switcher,  Private Relayt, FB container, Ducduck Private Essentials, Hoxx VPN. But I have them before.

I recetly added kabyle numbers here https://github.com/JRMeyer/common-voice-stats. I don't know if there is something changed that impacted the behavior.

**Comment by phirework** [comment]
Hi all, apologies for the delay in replying, the entire team (and indeed, the entire company) was engaged in all hands last week. The issue with Welsh vs. Kabyle is slightly different, and what's happening with Kabyle is a result of the single sentence record limit that rolled out last week - [Discourse post here](https://discourse.mozilla.org/t/single-sentence-record-limit-feature-release/62198). The reason sentences are no longer showing up as needing validation is because Kayble has approximately 500k clips recorded for only 90k sentences, so there are a lot of repetitions in the dataset already, and continually recording the same sentences will not improve the quality of the training data that gets produced. Right now, we'd really encourage you to focus community efforts on adding more sentences to record, either manually through the [sentence collector](https://common-voice.github.io/sentence-collector/#/) or by running the [sentence extractor](https://github.com/Common-Voice/cv-sentence-extractor) on a large corpus of text with the right open licensing, like [Kabyle wikipedia](https://kab.wikipedia.org).

**Comment by mozillakab** [comment]
@phirework in this case, please can we disable recording and show the link to to Sentence collector. I suggested a feature to display sentence collector url and invite people to validate.

**Comment by mozillakab** [comment]
@phirework  I will inform the community to go to Sentence Collector. Please, can we keep the recorded sentence that are not validated? We need them later for segmentation (for other use).

**Comment by SelyanKab** [comment]
@phirework, @mozillakab yes, it's a good idea, People should know that they have to add more sentences by showing the message and the URL adresse of sentence collector.
Thank you all

**Comment by mozillakab** [comment]
@SelyanKab we have thousands of sentences on CS waiting for validation. Please would you like post a publication on our FB page? Make a call, maybe we should organize a meeting? what action you think better to do? Within the last 3 months people say that SC server is very slow. I think that's why we got few validations from SC. I think we can create an issue on SC about this (slowness)

**Comment by SelyanKab** [comment]
@mozillakab Yes, I already post a publication on our Facebook page, calling the community.
 About the sentence collector  site, yes actually, it's too heavy to connect to it.

**Comment by MichaelKohler** [comment]
> Within the last 3 months people say that SC server is very slow. I think that's why we got few validations from SC. I think we can create an issue on SC about this (slowness)

> About the sentence collector site, yes actually, it's too heavy to connect to it.

That will be improved in the yet-to-be-released infrastructure update.

**Comment by nukeador** [comment]
Sorry I miss this, I was on vacations.

Please note that the recommended way to collect sentences is to use large sources of text using the sentence-extractor (wikipedia or others). This will produce the number of sentences you need with a significant less time investment from contributors.

See:

https://discourse.mozilla.org/t/readme-how-to-see-my-language-on-common-voice/31530
