### ISSUE TITLE
Meta description is not translatable, it always shows up in English

### ISSUE THREAD

**Issue by RobinvanderVliet** [common-voice/common-voice#2861]
**Describe the bug**
The meta description of the page https://commonvoice.mozilla.org/eo is not in Esperanto. When you share the link to that page with Telegram or Facebook, the description below it shows up in English, instead of in Esperanto.

**To Reproduce**
1. Share the link https://commonvoice.mozilla.org/eo with Telegram or Facebook
2. Look at the description near the link.

**Expected behavior**
The description should be translated.

**Screenshots**
![Telegram](https://user-images.githubusercontent.com/692029/89284716-7e6c2b00-d64f-11ea-84bc-258ee3d98451.png)
(Telegram)

![Facebook](https://user-images.githubusercontent.com/692029/89284752-8926c000-d64f-11ea-89f9-6b90c9d925e5.png)
(Facebook)

**Comment by ubaidisaev** [comment]
![image](https://user-images.githubusercontent.com/38039843/99968662-796fea80-2daa-11eb-856a-11d42a7ff0ff.png)
this problem appears in all languages, because it's hardcoded in English. i don't know what is the right way to add translation there. if someone give me any point i would be glad to work on this.

**Comment by le-jun** [comment]
I may be wrong and there probably is a more elegant approach to it, but couldn’t this issue be solved by adding one translated line for each language using the [`lang` attribute](https://html.spec.whatwg.org/multipage/dom.html#the-lang-and-xml:lang-attributes) in the [index_template.html](https://github.com/common-voice/common-voice/blob/main/web/index_template.html) file ?

`<meta lang="…" name="description" content="…" />`

**Comment by Heyhillary** [comment]
Thanks for your submitting this issues. A previous covers the same questions. So I will be closing issue #1051 but linking it here https://github.com/common-voice/common-voice/issues/1051

**Comment by zaccolley** [comment]
So I think unfortunately this is blocked by some pretty major work. 😿 

The application currently isnt serverside rendered meaning we can't easily change the meta tags in a way that will be picked up by Google, Facebook, Twitter's robots. As far as I can tell they tend to scrape the HTML sent by the server.

So two options I can see:

+ Implement serverside rendering for our static pages such as the homepage, about page. (A lot of work but is the way we should do it really)
+ Generating `index.html` pages for each locale. (Hacky, could work - but probably still a lot of work)

I've removed 'good first issue' because of this for now.

**Comment by zaccolley** [comment]
This has been changed in the 1.66.1 release: https://github.com/common-voice/common-voice/releases/tag/release-v1.66.1

> While it would have been nice to localize the text on the 'share card' when sharing the website this would have been a lot of work. We have decided to remove that text for now. 

Thanks everyone, hopefully in the future we can reimplement the full description that is localized!
