### ISSUE TITLE
Romanian typography - cedilla is used for composed s/t characters instead of comma

### ISSUE THREAD

**Issue by Steinhagen** [common-voice/common-voice#2971]
From the looks of things, about half of the strings use cedilla for the composed s and t characters instead of the correct comma.
https://en.m.wikipedia.org/wiki/Romanian_alphabet#Comma-below_(ș_and_ț)_versus_cedilla_(ş_and_ţ)
**(Wrong)** example taken from the current CV strings:
- Mai ales că toată lumea le **înţelege**.

**Correct** should be:
- Mai ales că toată lumea le **înțelege**.

First of all, what is the impact of this for training data models?
Secondly, how can this be fixed?

**Comment by ftyers** [comment]
As far as models are concerned, anyone training a model would have to perform the (simple) replacement before training, so it should have any effect there. When the first data with Romanian is released I would recommend adding a release note to this effect.

**Comment by phirework** [comment]
From a cleaning perspective, another thing you could do is add some language-dependant cleaning rules to the [Corpora Creator](https://github.com/mozilla/CorporaCreator#language-dependent-cleaning) for Romanian. 

As for fixing the sentences on Common Voice themselves, that would depend on whether the sentences came from sentence collector or something else. If from sentences collector, you'll need to generate a list of the sentences to be deleted and file an issue in the [sentence collector repo](https://github.com/Common-Voice/sentence-collector/). Once they're deleted over there the next SC export will remove the unrecorded sentences from the Common Voice repo as well. 

If they're not from the sentence collector, you can file an issue that corrects the sentences directly in the text file, and I can merge that in. That will also remove unrecorded sentences. We currently don't have a good way of altering sentences that already have clips associated with it, because each clip also independently records what the text that was read out was, hence the cleaning step at the corpus-generation level.
