### ISSUE TITLE
Fix microphone icon hover state bug

### ISSUE THREAD

**Issue by iraszl** [common-voice/common-voice#3021]
**Describe the bug**
On the page where you record your voice, on hover the microphone icon has an unintended square effect.

**To Reproduce**
1. Go to 'https://commonvoice.mozilla.org/en/speak'
2. Hover on 'microphone icon'
3. When entering the icon area you can see the error attached

**Expected behavior**
I'm unsure what the expected behaviour is meant to be. Probably a slight zoom in?

**Screenshots**
<img width="499" alt="bug" src="https://user-images.githubusercontent.com/11810851/108477797-aa3ebd80-72ce-11eb-8aa1-528edf76f527.png">

https://user-images.githubusercontent.com/11810851/108477839-b75bac80-72ce-11eb-8907-3beee3be7c8d.mp4

**Desktop or Mobile (please complete the following information):**
 - OS: Mac OS X 11.2.1
 - Browser: Safari
 - Version: 14.0.3

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: iMac
 - Model: 2018

**Comment by Dnouv** [comment]
@iraszl, it seems the issue is browser or OS-specific because I could not produce the same in Chrome(Windows), the color density around the mic icon increases on hover, while it becomes light on hover out(please refer to the screenshots below)
On hover,
![image](https://user-images.githubusercontent.com/61188295/116846640-5faebb00-ac06-11eb-8ed8-a95170454402.png)

On hover out,
![image](https://user-images.githubusercontent.com/61188295/116846545-1a8a8900-ac06-11eb-9dbd-f3a46047742c.png)

**Comment by phirework** [comment]
I am also unable to reproduce this on Safari 14.1 on MacOS 10.15.7, are you still experiencing the issue?

**Comment by zbianca** [comment]
I could reproduce it on Safari 14.1.1 on MacOS 11.4. Observe or hover the buttons during or soon after the hero translation occurs.
Adding `will-change: opacity;` to the .primary-button .background (line 22) fixes the problem.

Should I open a pull request?
