### ISSUE TITLE
Requesting Somali Language

### ISSUE THREAD

**Issue by Fatah2001** [common-voice/common-voice#3035]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add?
Somali

**Language code**
Please provide the ISO-639-1 code
SOM

**Language size**
Number of active speakers of this language in the world
over 50M

**Plural forms**
How would you translate the following in this language?

0 rocks        : 0 dhagax
1 rock         : 1 dhagax
2 rocks        : 2 dhagax
3 rocks        : 3 dhagax
4 rocks        : 4 dhagax
5 rocks        : 5 dhagax
10 rocks      : 10 dhagax
20 rocks      : 20 dhagax 
100 rocks    : 100 dhagax
1000 rocks  : 1000 dhagax 
I see 0 rocks on the ground : 0 dhagax baan dhulka ku arkaa
I see 1 rock on the ground  : 1 dhagax baan dhulka ku arkaa
I see 10 rocks on the ground : 10 dhagax baan dhulka ku arkaa
I see rocks on the ground    : dhagxaan baan dhulka ku arkaa 

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language

https://pontoon.mozilla.org/contributors/T4a2has715t7WYe_rgX7QnMbRXA/

**Comment by ftyers** [comment]
Hi @Fatah2001 thanks for your interest! The Common Voice team will probably not be active [until the middle of March](https://discourse.mozilla.org/t/update-on-common-voice-mozilla-foundation/74526), but in the meantime you can start [adding sentences](https://github.com/mozilla/common-voice/blob/main/docs/SENTENCES.md) to the [sentence collector](https://commonvoice.mozilla.org/sentence-collector/) and hopefully @peiying2 can take a look at the Pontoon request at the beginning of next week :)

**Comment by peiying2** [comment]
Hello @Fatah2001, I have set up [Somali](https://pontoon.mozilla.org/so/common-voice/) in Pontoon. Note the ISO-639-1 code for it is `so`. Let me know if you prefer `som` instead. 

I made you the locale manager because if you the one starting the group. This means all your work will go to staging (and later to production) without peer review. I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:
- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n community!
