### ISSUE TITLE
Should Thai language focus on one accent or use any accent?

### ISSUE THREAD

**Issue by ray1997** [common-voice/common-voice#3046]
So, while I notice other languages have accent setting. Should we add accent setting for Thai language?
While accent in Thailand only have 4 that is very well known, but when it comes to writing it would mostly be central-Thai
I'm recoding so far, I only found 1 text that is localize to North-eastern Thailand accent. If that's the case, should I translate that word back to central-Thai accent? Or just spoke it out in central-Thai accent with those words.

**Comment by ftyers** [comment]
Hi @ray1997 thanks for the question! At the moment the team is on a break, and soon Common Voice will be revisiting the whole accent/variant strategy, so it is not possible to add new accents at the moment.

If you see a sentence that is in a different variant to your own, you should either speak it out in your own way (if yo u are able), or you should skip it. Skipping sentences is fine and better than contributing some different audio.

**Comment by phirework** [comment]
Hi @ray1997, as @ftyers alluded to this is a somewhat complicated question. The most recent consensus from the team based on consultation with linguistics, ML experts, as well as the community is that instead of asking contributors to identify their own accents (which is often unreliable and inconsistent), it makes more sense to ask for the geographic boundaries of where that speech originates. This position is laid out in v5 of the [Common Voice Language and Accent Strategy](https://discourse.mozilla.org/t/common-voice-languages-and-accent-strategy-v5/56555). 

Common Voice is currently undergoing a transition, and while engineering resourcing has been consistent, there will be a new team on the Mozilla Foundation side that will be taking on more if the community and language governance aspects. Therefore, I would prefer to err on the side of not accepting new accents. However, if you can demonstrate consensus from linguists/other experts for a list of regions in Thailand/the diaspora that align with the Language and Accent strategy, I'd be happy to take a look at a pull request (see [Gaelician](https://github.com/common-voice/common-voice/pull/3045) as a recent example). 

If a sentence doesn't make any sense to you, feel free to skip it or report the sentence as being incorrect, and it will be excluded from the queue in the future. It's fine to read out a word in an unusual accent (given that machines will also need to codeswitch like this), but definitely don't change any of the words as-written on the card, as it means that validators are more likely to judge that clip as being inaccurate. I hope this helps!
