### ISSUE TITLE
The Romanian dataset contains some sentences in Irish, French and Italian. 

### ISSUE THREAD

**Issue by ftyers** [common-voice/common-voice#3075]
The Romanian dataset contains some sentences in Irish, French and Italian. 
```
omnilingo@itzpapalotl:~$ cat omnilingo/cv-corpus-6.1-2020-12-11/ro/*.tsv | cut -f3 | grep --color -i "[áćčđéíòšü]"
Există un vin rosé şi există altceva.
Ciò conclude il turno di votazioni.
Míle buíochas do mhuintir na hÉireann.
Poate ne puteți explica, dle Šefčovič.
Un foarte călduros bun venit, dle Đelić.
Nous en avons terminé avec les votes.
Vă mulţumesc foarte mult, dle comisar Šemeta.
München este una dintre aceste zone.
Guantánamo este un loc al torturii.
Vinul rosé este un produs artificial.
Vă mulţumesc foarte mult, dle comisar Šemeta.
Există un vin rosé şi există altceva.
München este una dintre aceste zone.
Guantánamo este un loc al torturii.
Vinul rosé este un produs artificial.
```

Also does Mozilla have a policy about sentences like the one about Guantánamo ?

**Comment by phirework** [comment]
It looks like those are all from the sentence-collector.txt file, which I would've expected to have caught them in terms of validation - @MichaelKohler is it possible to remove? 

I would also expect any clips associated with these sentences to have been marked as invalidated as they're the wrong language, and thus not be present in any of the test/dev/train sets. Are you concerned about specific impacts of this data pollution?

Re: Guantanamo - we generally don't make content-based judgment calls and contributors are always free to report sentences as offensive if they consider it such, or make a clear case for the need for its removal from the corpus entirely. In this instance, since it's only present in the wrong language, it may be a moot point anyway.

**Comment by ftyers** [comment]
> It looks like those are all from the sentence-collector.txt file, which I would've expected to have caught them in terms of validation - @MichaelKohler is it possible to remove?
> 
> I would also expect any clips associated with these sentences to have been marked as invalidated as they're the wrong language, and thus not be present in any of the test/dev/train sets. Are you concerned about specific impacts of this data pollution?

Not particularly, and you're right they're not in train-dev-test. I wasn't checking for that when creating the alphabet/validation files. 
 
> Re: Guantanamo - we generally don't make content-based judgment calls and contributors are always free to report sentences as offensive if they consider it such, or make a clear case for the need for its removal from the corpus entirely. In this instance, since it's only present in the wrong language, it may be a moot point anyway.

Sure! It's actually in the right language (that is Romanian in the Romanian data set) but I think that's right, if someone wants to report it they can.
