### ISSUE TITLE
Nyankole language

### ISSUE THREAD

**Issue by Atukunda-Gift** [common-voice/common-voice#3221]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add?
Nyankole
**Language code**
Please provide the ISO-639-1 code
ISO 639-3
**Language size**
Number of active speakers of this language in the world
3.4 million
**Plural forms**
How would you translate the following in this language?

0 rocks busha
1 rock orukiri
2 rocks enkiri eibiri
3 rocks enkiri ishatu
4 rocks enkiri ina
5 rocks enkiri itaano
10 rocks enkiri ikumi
20 rocks enkiri abiiri
100 rocks enkiri igana
1000 rocks enkiri rukumi
I see 0 rocks on the ground nindeeba hatariho rukiri ahansi
I see 1 rock on the ground nindeeba orukiri rumwe ahansi
I see 10 rocks on the ground nindeeba enkiri ikumi ahansi
I see rocks on the ground nindeeba enkiri ahansi

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language
giftatukunda6@gmail.com
**Language Script**
What is the name of the language scripts used to write your language ? e.g latin, Devanagari
Latin

**Comment by ftyers** [comment]
Hi @Atukunda-Gift ! Welcome to Common Voice :) The ISO code for Nyankole is `nyn`. You will also need to ask @MichaelKohler to add Nyankole to the [sentence collector](https://commonvoice.mozilla.org/sentence-collector).  In the meantime, if you have any other questions, you can join us on [Matrix](https://matrix.to/#/#common-voice:mozilla.org). Great to have you around!

**Comment by Heyhillary** [comment]
Hey @Atukunda-Gift,

Welcome to the Common Voice Community. I have now enabled Nyankole onto Pontoon https://pontoon.mozilla.org/nyn/common-voice/. 

However, is possible if you could create a pontoon account please, as I'm unable to find an account associated with your email address ?

Thanks in advance !

**Comment by Atukunda-Gift** [comment]
Hello @Heyhillary,

***@***.*** is the email I use on my pontoon account.

I have signed in following this link
https://pontoon.mozilla.org/nyn/common-voice/

Thank you

**Comment by Heyhillary** [comment]
Hey @Atukunda-Gift ,

Thanks for getting back to me.

Due to the privacy settings, I am unable to see the email in your most recent post. However, I was able to add your account associated with the first email.

To help get you started, here is some valuable information to help you as a manager for the language.The role of a manager means all your work will go to staging (and later to production) without peer review.

I hope through your work, there would be others joining you to collaborate on the different phases of this project. Here are a few docs that will help you with using Pontoon, working with other contributors, and localizing the file written in .ftl:

- [Pontoon user guide](https://mozilla-l10n.github.io/localizer-documentation/tools/pontoon/index.html)
- [Roles and responsibilities](https://mozilla-l10n.github.io/localizer-documentation/community/index.html)
- [Localizing in Fluent](https://mozilla-l10n.github.io/localizer-documentation/tools/fluent/index.html)
- [Common Voice web part project info](https://pontoon.mozilla.org/projects/common-voice/info/)

Thank you and welcome to the Mozilla l10n and Common Voice community!

If you have any questions please feel free to ask on [Matrix](https://chat.mozilla.org/#/room/#common-voice:mozilla.org)

**Comment by Atukunda-Gift** [comment]
This is great, thank you so much! @Heyhillary

**Comment by Atukunda-Gift** [comment]
This is great. Thank you so much! @Heyhillary

**Comment by Atukunda-Gift** [comment]
Hello @Heyhillary,
Could you please take me step by step on how to execute the release?

**Comment by phirework** [comment]
Hi @Atukunda-Gift, localization updates in Pontoon are automatically sync'ed to the Common Voice repo and you do not need to do anything to release them. Newly translated strings will automatically show up on our dev server every few days (https://dev.commonvoice.mozilla.org), and are released to production every two weeks. The most recent release was August 11th. However, new languages are not visible on production until they are 90% localized.
