### ISSUE TITLE
Run Common Voice as a docker locally to create an additional domain specific dataset.

### ISSUE THREAD

**Issue by rpostulart** [common-voice/common-voice#3240]
I would like to Run Common Voice in our company to create our own dataset that is specific to a domain context. 
I would like to use this training set on top of the common voice dataset. 

Is it possible to run Common Voice locally for example via Docker?

**Comment by ftyers** [comment]
Dear @rpostulart this does not look like a bug report. Could you please open a topic on [Discourse](https://discourse.mozilla.org/c/voice/239)? Thanks!

**Comment by MichaelKohler** [comment]
@rpostulart yes, however Mozilla does not support self-hosted instances per se. There is a tutorial on how to get it running with Docker for local development here: https://github.com/common-voice/common-voice/blob/main/docs/DEVELOPMENT.md . These settings might or might not be good defaults for running it in production though, so that's up to you to make sure.

**Comment by rpostulart** [comment]
Done: https://discourse.mozilla.org/t/run-common-voice-standalone-via-docker/84832
