### ISSUE TITLE
Image voice caption feature?

### ISSUE THREAD

**Issue by dakuo** [common-voice/common-voice#3349]
Does the coding UI system also support voice-captioning collection for  image-based data ? Meaning, instead of presenting a text-based sentence to the user, we replace it with presenting an image.

**Comment by phirework** [comment]
The system does not support captioning for image-based data and we have no plans for adding such support. You're welcome to fork the code and modify it yourself, though please note that you would also need to build in a step where someone transcribes what the user described, and modify the validation step so that both the utterance and the transcription are verified.
