### ISSUE TITLE
Autoplay option in listening mode

### ISSUE THREAD

**Issue by rugk** [common-voice/common-voice#337]
One could save a click per sentence, when one could enable an "autoplay mode" when listening/checking sentences.

**Comment by saddy001** [comment]
I'd like that too and I think it would encourage people to check even more sentences.

**Comment by mikehenrty** [comment]
Good idea!  @jdittrich, any ideas where this checkbox could go?

**Comment by jdittrich** [comment]
I wonder if we should not implement keyboard shortcuts for that instead – see "Flexibility and efficiency of use" in [Nielsens Heuristics](https://www.nngroup.com/articles/ten-usability-heuristics/) and have shortcuts for "yes", "no" and "(re)play".

**Comment by mikehenrty** [comment]
Oooh, I like that idea @jdittrich ! Can we open a separate bug for that?

For this one, if we have the shortcuts maybe is doesn't make sense for a checkbox? Or does it?

Another thing we can do is detect if they have listened to 2 or 3 in a row, and then start autoplaying automatically.

Thoughts?

**Comment by Omniscimus** [comment]
> 2 or 3 in a row, and then start autoplaying automatically

Might come a little unexpected if only after the 3rd time. Could be good to start autoplaying just after the first time. (not immediately because that's weird when the page first loads.) We could enable autoplay the moment a user first clicks Yes or Nope?

I think shortcuts are a great idea but even if we have shortcuts it will still be useful to have autoplay imo. Without autoplay you still have to perform an extra option, in this case a key press instead of a click

**Comment by jdittrich** [comment]
>   2 or 3 in a row, and then start autoplaying automatically

It might work, but doing things *automatically* the right way, is usually about 5-10 times more work in testing. So if no one has a significant amount of time for creating it and testing with users I would not recommend it. 

That’s also why I would keep the current (non-autoplay) behaviour and first get the keyboard shortcuts into place. Once we have that I would suggest to look into autoplay again.

**Comment by rugk** [comment]
Why not do what @Omniscimus suggested? IMHO that behavior would be fine and intuitive. :smiley:

**Comment by jdittrich** [comment]
@rugk As written above, because "automatic" behaviour in UI design are often brittle. If we would have…

* an established UI that works the way as suggested, 
* we know it works well, and 
* people who use *voice.* know it,  

…then I think it is fine to implement (because ["Intuitive equals familiar"](http://www.asktog.com/papers/raskinintuit.html)). If we don’t, I would avoid it as long as no one does usability testing and iterations for it.

**Comment by rugk** [comment]
The problem with keyboard shortcuts is, that they don't satisfy the third point. People don't know it.

And:
> Without autoplay you still have to perform an extra option, in this case a key press instead of a click

**Comment by saddy001** [comment]
I think a simple "Autoplay"-checkbox might catch the "drive-by people" on the site in the first place. Later keyboard shortcuts could be added.

**Comment by Djfe** [comment]
so, some ideas of mine:
batch listening

3 texts below each other

each has yes, no and replay button

each text is in a container
while it plays it shows the percentage of playback in it's background (darker grey background that grows to the right of the container according to the playback percentage)

1/2s after one is done: start playing the next one text back
the user can press a button for the upper texts even after that. if he/she decides to replay one text, then it will go back and play the next text after that. 

rotate through: 1 2 3 1 2 3

and do sufficient buffering
I tend to have to wait for audio to buffer (1-3s)
especially on mobile, it's annoying and eats up time


on mobile:
maybe even use gestures like swipe for this

swipe away -> no
ignore -> yes (once 3 items played, without swiping, it will be auto answered with yes)

swiping away -> the next text appears right below the one you just swiped away (already while you swipe) (no moving animations)

**Comment by rugk** [comment]
Haha, I like that Android option. Maybe just make it really like Tinder - correct and wrong in two directions. 😆

**Comment by jdittrich** [comment]
FYI: the related #379 (Keyboard Shortcuts) has been implemented.

**Comment by Djfe** [comment]
I'm interested in maybe implementing this or starting with it.
But only if noone else is already working on it.

I think it makes the most sense to give batch validation it's own page instead of displaying it on the front page.
Do we want to keep the single validator on the front page or link to the validation page?

Is preloading up to 6 items too much?
I would display 3 items at a time and preload one for each of them in the background (including the audio)
Should we preload the Audio in typescript (blob) or add audio elements earlier to the DOM than they are displayed?
My preference would be the latter.

**Comment by mikehenrty** [comment]
> Do we want to keep the single validator on the front page or link to the validation page?

We used to have a separate page for the listen widget, but nobody used it. Let's keep the listen box on the homepage for now.

> Is preloading up to 6 items too much?

Seems like overkill to me. 2 or 3 clips should do it, so long as we are keeping that continually loaded and ready to plan.

> Should we preload the Audio in typescript (blob) or add audio elements earlier to the DOM than they are displayed?

DOM is fine here I think.

**Comment by magopian** [comment]
I've experimented with autoplay and tinder-like swiping in a small proof of concept: https://magopian.github.io/common-voice-validate/

Swiping only works on mobile in this demo, so if you want to test it on firefox for desktop, you can do so by enabling the responsive view, and the "simulate touch events" button.

The code lives at https://github.com/magopian/common-voice-validate : it's written in Elm without much consideration for clean/maintainable/quality code for now.

**Comment by Djfe** [comment]
this is not even that different from the current approach on the staging server:
https://voice.allizom.org/en/listen

@Gregoor it would be nice if the yes/no buttons would automatically play the next clip :)
(maybe with a profile setting to activate it (for familiar users))

**Comment by Gregoor** [comment]
> I've experimented with autoplay and tinder-like swiping in a small proof of concept: https://magopian.github.io/common-voice-validate/

Very cool! We could have that as another method of interaction on mobile (afaik Tinder has buttons + swipes as well).

RE autoplay #337

**Comment by m-branson** [comment]
Auto-play sounds great. Seems it would be best on all clips after the first (don't want to surprise anyone) and ideally there would be a way to enable/disable within the session. Yes, as @Djfe mentioned, profile settings are a good spot for it as well. Mostly as a universal setting though. Would prefer to see it as a UI element also for easier usability & awareness. 

Swipe also sounds great. These are all natural gestures that will only make the experience more polished. Where do I sign up? 😉  e.g. @Gregoor what do you need to make any of this happen?

**Comment by Gregoor** [comment]
😁 For swiping I don't need anything. I'll make it happen then.
