### ISSUE TITLE
Remove branch protection from main for Pontoon

### ISSUE THREAD

**Issue by flodolo** [common-voice/common-voice#3440]
This morning I woke up to about 2k errors in Pontoon from Common Voice (cc @mathjazz)

```
Feb 01 13:10:29 mozilla-pontoon app/worker.1: Failed to sync locale fr for project common-voice due to commit error: remote: error: GH006: Protected branch update failed for refs/heads/main. 
```

The branch where Pontoon writes localization needs to be open, not protected.

I've disabled sync for this project until the issue is resolved.

**Comment by MichaelKohler** [comment]
This is not only needed for Pontoon, but also for the Sentence Collector sentence exports, as well as the string exports: https://github.com/common-voice/sentence-collector/actions/runs/1781954589/attempts/1

**Comment by zaccolley** [comment]
Thanks both, sorry for the noise created. I have removed the branch protection.

Might need some help understanding how Pontoon works in other repositories, we made the change to protect the main branch because we'd like to eventually move towards a continous deployment releases where the main branch would be essentially production.

Would this imply to be able to do this we'd have to move away from a monorepo setup that we currently have?

**Comment by mathjazz** [comment]
Hey Zac, most projects use separate -l10n repositories to allow for using protected branches on the main development repositories. Another benefit of such setup is to avoid Pontoon commits from overflowing the commit history.

**Comment by flodolo** [comment]
See also https://mana.mozilla.org/wiki/pages/viewpage.action?pageId=144147931#RequestlocalizationfornewProductUI(community)-Repositorystructure

**Comment by zaccolley** [comment]
@flodolo amazing thank you
