### ISSUE TITLE
Telugu language

### ISSUE THREAD

**Issue by venugudavalli** [common-voice/common-voice#3508]
Use this template to request a new localizable language that is currently not available [on Pontoon](https://pontoon.mozilla.org/projects/common-voice/).

Note: This issue only applies to the web interface language - in order to activate language contributions on Common Voice you will also need to ensure 5,000+ sentences are available to be read in that language. Please refer to the [full Language documentation](https://github.com/mozilla/common-voice/blob/master/README.md) for more details.

**Language name**
What language would you like to add?

**Language code**
Please provide the ISO-639-1 code

**Language size**
Number of active speakers of this language in the world

**Plural forms**
How would you translate the following in this language?

0 rocks
1 rock
2 rocks
3 rocks
4 rocks
5 rocks
10 rocks
20 rocks
100 rocks
1000 rocks
I see 0 rocks on the ground
I see 1 rock on the ground
I see 10 rocks on the ground
I see rocks on the ground

**Pontoon manager**
Please link to the Pontoon account of the person who should be listed as the community manager of this language

**Language Script**
What is the name of the language scripts used to write your language ? e.g latin, Devanagari

**Comment by ftyers** [comment]
Dear @venugudavalli, thanks for submitting this request. I've looked and it seems that Telugu is already [enabled in Pontoon](https://pontoon.mozilla.org/te/common-voice/). If you would like more help with getting started with Common Voice please feel free to join us on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org) :)

**Comment by Heyhillary** [comment]
Hey @venugudavalli,

How are you finding the project so far ?

Since your language joined we updated the milestones you need to reach for your language to be launched for voice data collection which are;

1. Localisation is >60% you are just off by 16%
2. Language Bands, your language only needs 2000 CC0 sentences .

To reach the latter you can use a variety of methods such as;
-  [sentence collector](https://commonvoice.mozilla.org/sentence-collector/#/how-to) to contribute CC0 licensed content
- [bulk submission](https://common-voice.github.io/community-playbook/sub_pages/text.html) to contribute large files of sentences in txt format
-  [sentence extractor](https://github.com/Common-Voice/cv-sentence-extractor) from large sources of public domain text, with a focus easy-to-read corpus and Wikipedia.

If you have any questions, please let me know or join us on [element ](You can use a variety of methods such as;

    [sentence collector](https://commonvoice.mozilla.org/sentence-collector/#/how-to) to contribute CC0 licensed content
    [bulk submission](https://common-voice.github.io/community-playbook/sub_pages/text.html) to contribute large files of sentences in txt format
    [sentence extractor](https://github.com/Common-Voice/cv-sentence-extractor) from large sources of public domain text, with a focus easy-to-read corpus and Wikipedia.)
