### ISSUE TITLE
[BUG] The About Us page doesn't respect page language choice

### ISSUE THREAD

**Issue by JakubDrozd** [common-voice/common-voice#3669]
**Describe the bug**
When I go to the About Us page, some page text doesn't respect the language choice and the languages are mixed up.

**To Reproduce**
1. Navigate to the About Us page.
2. Try changing the site language a few times.

**Expected behavior**
The whole page should be in the chosen language.

**Screenshots**
![2022-04-20](https://user-images.githubusercontent.com/70533786/164204871-8047b613-0e8f-42dd-9d01-b81d68002ed5.png)
![2022-04-20 (1)](https://user-images.githubusercontent.com/70533786/164204861-e55226e3-74f3-4058-ab5d-a02284b56f42.png)
![2022-04-20 (2)](https://user-images.githubusercontent.com/70533786/164204867-c2f1531a-a448-42b1-944a-4808f388c119.png)

**Desktop or Mobile (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 100

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type:
 - Model:

**Additional context**
The browser language and page language is Polish. But you see in the screenshots that Polish is mixed up with Russian and English. I can help with the translation.

**Comment by Heyhillary** [comment]
Dear @JakubDrozd 
Thanks for raising this issue - I started to investigate what was happening on the Pontoon side to understand the bug your raised. 

1. As you may be aware contributors organise via Pontoon to localise Mozilla projects like Common Voice. I noticed for Polish that some strings of the website [are not translated ](https://pontoon.mozilla.org/pl/common-voice/web/locales/en/messages.ftl/?status=missing&string=242637). Would you be interested in helping translate the pages please?

Translating the strings enable pages to be in people's native languages when they enter the site. 

2. I checked another language, Catalan, that has nearly 100% translation and the issue is not found there.

Please let me know if you can help, thanks again for raising the issue !

**Comment by JakubDrozd** [comment]
Yes, I can help. Polish and English are my native languages. Maybe the mistake has to do with browser languages.

**Comment by Heyhillary** [comment]
Hey @JakubDrozd ,

Thanks so much for offering help. To get you started please follow the next steps;
1. Please create an account on Pontoon -> [Pontoon](https://pontoon.mozilla.org/teams/ )
2. Please watch this video explainer -> [Video](https://drive.google.com/file/d/1YVyHUPaw2oiVdZZ7_pg607cIMq0YDMcw/view?usp=sharing)
3. Please then share with me your pontoon profile URL - so I can add you as a translator 
4. Start to contribute !
5. Connect with the wider community via [element](https://chat.mozilla.org/#/room/#common-voice:mozilla.org) or and [discourse ](https://discourse.mozilla.org/c/voice/239)
If you need anything please let me know !

**Comment by JakubDrozd** [comment]
Profile: https://pontoon.mozilla.org/contributors/jyu_ldRWpzy0X4D4AqQXxlK4MqE/

**Comment by Heyhillary** [comment]
Thank you @JakubDrozd you should know have translator permissions

**Comment by JakubDrozd** [comment]
> Thank you @JakubDrozd you should know have translator permissions

I still don't have the permissions.
