### ISSUE TITLE
Updated "end of clips" message in validation not translated for other languages

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3819]
**Describe the bug**
The english " end of clips" message in validation has been updated.
See screenshot1
![Screenshot_20220929-175016](https://user-images.githubusercontent.com/92784377/193086001-9a656772-158d-4612-bf60-bb9fbd9a23be.png)

In other languages the old translated message (there are no more clips to validate) is presented to the contributor 
see screenshot 2 (german)
![Screenshot_20220929-173831](https://user-images.githubusercontent.com/92784377/193086142-a7fb348f-7520-4aa6-8196-b6b6978d580f.png)

**Expected behavior**
The new (updated) english message is translated and displayed to the contributor in non english sections.

**Mobile (please complete the following information):**
 - OS: Android13 GrapheneOS TP1A.220905.004.A1.2022092300(beta)
 - Browser Vanadium
 - Version [e.g. 22] 105.0.5195.136

 **Hardware :**
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**

**Comment by ftyers** [comment]
Did you check in Pontoon?

**Comment by robovoice1** [comment]
Thanks for the direct link @ftyers !

Suggested new german translation, with mentioning refresh page or try again later, waiting for approval.

**Comment by HarikalarKutusu** [comment]
It is OK on the staging server:

https://commonvoice.allizom.org/tr/listen

![image](https://user-images.githubusercontent.com/8849617/193207208-7c2f7b2b-3d26-4dc6-a973-a46749d551cc.png)

But the last website release is on 21st.

I think the following issue is also related, because probably those values are cached in the store...
https://discourse.mozilla.org/t/why-do-total-hours-differ/105847
