### ISSUE TITLE
[BUG] Long german words (nouns) are cut off in summary before submitting

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#3844]
**Describe the bug**

Long german words (2 or more combined nouns) are cut off or do not fit the "bubble" in the summary of the recorded clips before submitting.
Please see screenshot
The german word "Gründungsdirektor" (founding director) is missing the last letter "r"

**Expected behavior**

The full sentence is presented to the contributor when tapping the play button 

**Screenshots**
![Screenshot_20221026-154615](https://user-images.githubusercontent.com/92784377/198375439-86b7f47f-1e14-4944-9e8e-80b8e842f8d8.png)

**Mobile (please complete the following information):**
 - OS: Android 13, GrapheneOS latest beta release
 - Browser vanadium
 - Version [e.g. 22] latest version

 **Hardware
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**

This is a special case for the german language (combined 2 or more nouns written as 1 big word)

**Comment by robovoice1** [comment]
More examples:
![Screenshot_20221028-095026](https://user-images.githubusercontent.com/92784377/198535653-78fa8c1d-117d-48de-a39e-97b93c5200a9.png)
"Präsidentschaftskandidat" (presidantial candidate) is not fitting. Please zoom in the screenshot.

![Screenshot_20221028-095042](https://user-images.githubusercontent.com/92784377/198537103-166863d2-3ee0-4710-8444-4a0bf0934f5d.png)
"Generalversammlung" (general assembly)

![Screenshot_20221028-095132](https://user-images.githubusercontent.com/92784377/198537559-9c6ad68c-c3e0-4114-885f-c8f3404eb975.png)
"Septemberwochenende" (september weekend)

**Comment by janvi01** [comment]
hey @robovoice1 @moz-rotimib I would like to work on this issue if available.

**Comment by moz-rotimib** [comment]
Hello @janvi01 this ticket is still open. Feel free to pick it up and open a PR with a fix. Thanks for your contribution! ❤️

**Comment by adarrssh** [comment]
Currently, we cannot record voices in development mode. How can we address this issue and test voice recording in development mode?


<img width="1300" alt="Screenshot 2023-09-12 at 7 36 07 PM" src="https://github.com/common-voice/common-voice/assets/85433137/eca901fa-1d8f-43e3-b064-2575ab67e8e4">

**Comment by moz-rotimib** [comment]
Hello @adarrssh the reason you're not seeing the option to record your voice is because English is probably not imported in your local setup. You can verify this by checking the call to the `languages` endpoint (in your Network tab) and checking what the `is_contributable` value for English is. If it is 0 then you probably need to import English sentences in your local setup.

So after running `docker-compose up` make sure that the sentences for each language is imported - you don't have to import all languages because it could take a long time. So having 10 - 15 languages (including your native language is a good option).

Let me know if you have any other questions. Thanks ❤️

**Comment by adarrssh** [comment]
Yeah, I check the `is_contributable` is zero only.
Could you please also tell the procedure to add the languages as I am not able to figure out that part ?
Also is there any docs for that on the github documentation?


<img width="577" alt="Screenshot 2023-09-12 at 8 17 03 PM" src="https://github.com/common-voice/common-voice/assets/85433137/06850e70-03ca-4445-b342-0e23c02777f2">

**Comment by adarrssh** [comment]
This is my .env-local-docker file. The `CV_IMPORT_SENTENCES` variable has always been set to true only.
Do you see any issue with these env credentials ?

```
CV_DB_ROOT_PASS="voicewebroot"
CV_MYSQLHOST="db"
CV_S3_CONFIG='{"endpoint": "http://s3proxy:80", "accessKeyId": "local-identity", "secretAccessKey": "local-credential", "s3ForcePathStyle": true}'
CV_S3_LOCAL_DEVELOPMENT_ENDPOINT="http://localhost:9001"
CV_ENVIRONMENT="local"
CV_PROD="false"
CV_IMPORT_SENTENCES="true"
CV_EMAIL_USERNAME_FROM="commonvoice@mozilla.com"
CV_EMAIL_USERNAME_TO="commonvoice@mozilla.com"
CV_REDIS_URL='redis'
CV_AUTH0_DOMAIN="dev-k1e5jfy6qng5zufk.us.auth0.com"
CV_AUTH0_CLIENT_ID="aWlH8KShVhMBA1zJ1PnxSkKGAYxfaRMp"
CV_AUTH0_CLIENT_SECRET="dZ5pgNEBHRCvGia3O191UJYNGZyuXWRqeR3qL-96wfsDxo-3D9cdOSRbMuoEe9Fp"
```

**Comment by adarrssh** [comment]
Okay, will I be able to see this in the terminal(import process)👀 ?

**Comment by moz-rotimib** [comment]
Yes. I can't remember the exact wording now but it will show something like:

Importing en
Importing fr

**Comment by adarrssh** [comment]
Hey, I waited for 2 hours and I don't think my system has imported the languages. 
Can you please check the below logs and tell me if there is something wrong in that ?
Thanks 

<img width="1287" alt="Screenshot 2023-09-13 at 12 07 26 PM" src="https://github.com/common-voice/common-voice/assets/85433137/1bc0774d-38ed-4b8a-80ff-c1dcd542b59c">
<img width="1243" alt="Screenshot 2023-09-13 at 12 07 39 PM" src="https://github.com/common-voice/common-voice/assets/85433137/933031ab-2b36-49fc-a90b-8f7fb3ae31e2">
<img width="1434" alt="Screenshot 2023-09-13 at 12 07 53 PM" src="https://github.com/common-voice/common-voice/assets/85433137/bf88e6ec-2977-49b7-9b64-fecca6cf46b2">

**Comment by moz-rotimib** [comment]
Can you run `yarn import-locales` and see what the outcome is?

**Comment by adarrssh** [comment]
**It says that it can't find the command `yarn import-locales`**

<img width="654" alt="Screenshot 2023-09-13 at 3 58 48 PM" src="https://github.com/common-voice/common-voice/assets/85433137/1ea4a0d2-441c-4244-a5de-7eb5af8318d9">

**Comment by moz-dfeller** [comment]
Hey @adarrssh ! Thank you for your interest in the project! So, to make it short: 
* uncomment the following lines in [server.ts](https://github.com/common-voice/common-voice/blob/3f7ef2c94037f53d43f750036317ea0a454089d4/server/src/server.ts#L257C1-L259C11):    
```ts   
      // if (doImport) {
      //   await importSentences(await this.model.db.mysql.createPool());
      // }
```
You can just set `doImport` to `true` for the first run or set the env variable `CV_IMPORT_SENTENCES=true`. I would comment it out again after you're done. It takes a long time but you should see logs in the terminal that say that a specific locale has been imported.

The standard import has been deprecated, but since there is a need for the local development environment to import sentences, we left this code snippet there for now until we find a better solution.

**Comment by adarrssh** [comment]
Thanks @moz-dfeller , Now I am finally able to see the imports in my logs.
I still have few questions to ask . 
1. Do I need to do anything else to record the voices in development mode ?
2. Do I need to import all the languages?


<img width="1438" alt="Screenshot 2023-09-13 at 5 24 12 PM" src="https://github.com/common-voice/common-voice/assets/85433137/ad2f5520-4edf-4e8d-908f-9d4139be54e4">

**Comment by moz-rotimib** [comment]
> Do I need to do anything else to record the voices in development mode?

Once you have imported a language locally you should be able to record clips for that language - I don't think you have to do anything extra.

> Do I need to import all the languages?

You don't need to import all languages (you can if you want to it just takes a long time to import all the languages). When you have imported as many languages as you want, you can quit the process and don't forget to set the `CV_IMPORT_SENTENCES` flag to `false` so you don't do the import every time you start common voice.

**Comment by adarrssh** [comment]
We are currently using an external library for the tooltip (`react-tippy`). In order to fix the text overflow issue, I increased the maximum width of the tooltip.


Here's the changes 


**Before fix** 
(text overflowing from the tooltip)

https://github.com/common-voice/common-voice/assets/85433137/42761379-488e-49a8-a620-633ea7263ccd

**After fix** 


https://github.com/common-voice/common-voice/assets/85433137/62f23a42-c54e-4ba9-9717-86ff13644a2f



https://github.com/common-voice/common-voice/assets/85433137/6cd074de-71ed-4720-b22a-802039cdd04d
