### ISSUE TITLE
[BUG] Delta Segment 11.0 downloads lacking TSV files

### ISSUE THREAD

**Issue by mmcauliffe** [common-voice/common-voice#3858]
**Describe the bug**
When I downloaded Delta segments for 11.0 across a number of languages, they all only contained the clips folder and didn't have any TSVs for clip information.

**To Reproduce**
1. Go to https://commonvoice.mozilla.org/en/datasets
2. Click on Common Voice Delta Segment 11.0
3. Extract files from archive
4. See only clips directory

**Expected behavior**
I expected TSVs separated into validated, other, etc like the Delta segment for 10.0

**Screenshots**

**Desktop or Mobile (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type:
 - Model:

**Additional context**

**Comment by mozgzh** [comment]
Thanks for filing the issue. This problem will likely have to wait to be resolved until the next release due the nature of our data release process

**Comment by paulbauriegel** [comment]
@ftyers The bug seems to be still present even after the newer releases

**Comment by SIMONDSKNIGHT** [comment]
Still Broken

**Comment by HarikalarKutusu** [comment]
v11.0 is pretty old. I wonder why you are seeking it in 2025? Is this a specific workflow related?
And instead of delta releases you can also use full releases which are OK for that release.
I think "It will be fixed in the next release" means that there will be no such problem in v12.0 delta.
AFAIK, the records in the database do not have any timestamp, so one cannot re-generate a dataset release from the past, using existing coding. The only way to do it is writing special purpose code to get diff between full versions of v12.0 and v11.0.

If you need FULL metadata from a language for v11.0, please ask here with the language code and I can provide it. If you are just seeking for some statistical info, there are tools which provide that.

**Comment by SIMONDSKNIGHT** [comment]
Thank you for the very timely response. 
I'm currently working with the restriction of being unable to use anything from and including release 9. the delta releases allow me to avoid downloading the vast majority of the audio which would be unusable to me. If you would give me the metadata for "en" in v.11, I would be beyond thankful.

**Comment by HarikalarKutusu** [comment]
Here is the metadata file which I named `cv-corpus-11.0-2022-09-21-en-metadata-only.zip`.

https://drive.google.com/file/d/1N7DXtlMSAWBLApRbwJU2-164vU0iYpFO/view?usp=sharing

- Copy `cv-corpus-10.0-2022-07-04/en` directory to `cv-corpus-11.0-2022-09-21/en`
- Copy/move the clips in the clips directory from v11.0 delta into `cv-corpus-11.0-2022-09-21/en/clips`
- Copy and override the metadata files in `cv-corpus-11.0-2022-09-21/en`

That's it...
