### ISSUE TITLE
LOCALIZATION REQUEST: Fräapmer Platt

### ISSUE THREAD

**Issue by matteswiegmann** [common-voice/common-voice#3893]
**Language name**
Fräapmer Platt

**Language code**
?

**Language size** 
2

**Plural forms**
How would you translate the following in this language?

0 rocks
1 rock
2 rocks
3 rocks
4 rocks
5 rocks
10 rocks
20 rocks
100 rocks
1000 rocks
I see 0 rocks on the ground
I see 1 rock on the ground
I see 10 rocks on the ground
I see rocks on the ground
->
Kein Stäin
äin Stäin
Twäi Stäine
Dräi Stäine
Veer Stäine
Füife Stäine
Täihen Stäine
Twintig Stäine
Hunnert Stäine
Diusend Stäine
Ick säh käin Stäin upö Äeen
Ick säh äin Stäin upä Äeen
Ick säh täihen Stäine upä Äeen
Ick säh Stäine upä Äeen

**Pontoon manager**
[Pontoon account](https://pontoon.mozilla.org/contributors/einmatze/)

**Language Script**
latin

**Sentence Requirement Band**
- [x] Band A

1. Why do you want to take part in Common Voice ?
We want to save a dialect.

2. Would you like to have a follow up conversation regarding community building ?
No, thanks.

**Comment by emlewjong** [comment]
I'm the Product Lead for Common Voice - thank you so much for your patience. We will have more community support joining in a couple of weeks, and their first priority will be making sure your request is followed up!

**Comment by ftyers** [comment]
Dear @einmatze, could you let us know what the ISO language code is for Fräapmer Platt?

**Comment by EinRolland** [comment]
Hi @ftyers , hi @emlewjong , 
I'm joining to help in this issue of saving the dialect "Fräapmer Platt". 
@matteswiegmann and I are new in this terrain. 
How can we proceed? The special dialect, we want to save, is spoken in just one little village (coordinates: (52.3809633, 8.6644846) ) and has no ISO language code. . 
So - what can we do now?

**Comment by ftyers** [comment]
Dear @EinRolland thanks for your interest. Where is it spoken exactly? I wasn't able to find Fräapmer on any maps.

**Comment by ftyers** [comment]
I looked at the coordinates, and it appears to be south of Bremen and west of Hannover. This would put it with [Northern Low Saxon](https://en.wikipedia.org/wiki/Northern_Low_Saxon), language code `nds`.
![imatge](https://github.com/common-voice/common-voice/assets/449545/90f78938-750a-4956-b15d-a184b3e6815f)

**Comment by EinRolland** [comment]
Dear Francis,
thank you for your information.
In fact, the village in question called "Frotheim" (after incorporation now a district of Espelkamp) is located about 100km south of Bremen, about 50km east of Osnabrück and about 25km north-west of Minden. I've put an "X" in the correct place on your map. We called the project "Fräapmer Platt" and not "Frotheim" because that's what the dialect calls itself in his own dialect (translated it would be "Frotheimer Platt" for "Dialect of Frotheim").

The dialect of the inhabitants of the surrounding villages is relatively uniform. They understand the Frotheimers and vice versa. But our native speaker, whom we would like to allow to have his say on all pronunciations, is convinced that "Fräapmer Platt" has a lot in common with Flemish.
Since the village is in the named area, do we enter the code of "Northern Low Saxon"?

Some time ago, our native speaker (now 91 years) played a key role in a local group (all of them, with the exception mentioned, have since died) led by an elementary school teacher, which over the years collected, wrote down and published a collection of words, pronunciations and idioms in a book with a very small edition. We could provide excerpts from it if that helps for the next steps.

Best regards
![230830-karte-x-saxonian-dialects](https://github.com/common-voice/common-voice/assets/143338161/f1a74692-6cef-4a3b-b2a4-8544cd489043)

**Comment by ftyers** [comment]
In that case, the language code `wep` may be applicable, for [Westphalian](https://en.wikipedia.org/wiki/Westphalian_language). We currently have no way of making projects for individual variants of a language, variants are supported under their language code, and then the variant may be specified in the profile of each speaker. If you would like to go ahead, let me know.

**Comment by EinRolland** [comment]
Yes we would like to go ahead.

**Comment by ftyers** [comment]
Apologies for the delay, the project is available [here](https://pontoon.mozilla.org/wep/common-voice/). When you have made some translations, let me know and I will make you translator. If you have any further questions, please feel free to contact via email, or on [Matrix](https://app.element.io/#/room/#common-voice:mozilla.org).
