### ISSUE TITLE
Submit and Shortcut buttons hidden when screen size reduces to 764px [BUG]

### ISSUE THREAD

**Issue by shashankcoc** [common-voice/common-voice#3997]
**Describe the bug**
Lower buttons Submit and Shortcut gets hidden after certain pixels

**To Reproduce**
1. Go to ['...'](https://commonvoice.mozilla.org/en/speak) by decreasing size to 764px
2. Botton Invisible
3. Go back to size >764px
4. See the buttons again

**Expected behavior**
Both the buttons should be visible i.e., Responsive buttons 

**Screenshots**
Before changing size

![correctly_displays](https://user-images.githubusercontent.com/44526306/229444775-a24594da-b3ff-410a-aff1-0c98143b187e.png)

After changing size -- **Buttons vanished**

![invisible_buttons](https://user-images.githubusercontent.com/44526306/229444812-854f96e8-82eb-4089-93e9-059ebfd9ce61.png)

**Desktop or Mobile (please complete the following information):**
 - OS: Windows 10
 - Browse: Chrome Mozilla 
 - Version 111.0.5563.147 (Official Build) (64-bit)

**Additional context**
This whole scene is about the responsiveness of the web which can easily be tackled by adding media queries.
Please revert back if you think i can work on this issue.

**Comment by moz-rotimib** [comment]
Hello, @shashankcoc thanks for filing this issue.

I've looked at this issue and I don't think it's a bug for the following reasons:

1. The submit button is visible on smaller screens after you record 5 clips (check the attached screenshot)

<img width="724" alt="Screenshot 2023-04-03 at 09 32 13" src="https://user-images.githubusercontent.com/113194143/229458755-3fbf5809-6cb5-41fc-9255-f34d1c99cc36.png">

2. The shortcuts button is hidden on smaller devices because it doesn't make sense to show it on devices that don't use a computer keyboard as the primary means of interacting with the Common Voice.

Please let me know if you have any further questions or need clarification.

**Comment by shashankcoc** [comment]
Alright got your point! 
yes sure, I'll be happy to work on the padding and margin issues. Thanks.

**Comment by moz-rotimib** [comment]
Thanks. I'll close this issue now
