### ISSUE TITLE
[BUG] On new sentence collector/review Report button should not be presented

### ISSUE THREAD

**Issue by HarikalarKutusu** [common-voice/common-voice#4047]
The report button's purpose is to report sentences that are already in text-corpus, recorded or not yet recorded. These sentences get logged into reported.tsv eventually.

On the other hand, while reviewing the added sentences, you are presented with NO, where you downvote regardless of the reason. You should not report a misspelling, incorrect grammar etc, but you should press NO, so that the sentence does not find its way into the text corpus to be recorded.

This is UNLESS the system is keeping track of the sentence rejection reasons in a separate database table, but then the NO button should not be presented.

**Comment by jessicarose** [comment]
Hello! Sorry for the wait on the reply. The report button is to flag sentences that are unsuitable due to reasons like copyright, hate speech or other issues that make them immediately unsuitable for the corpus and these will be flagged to the team.

As a general rule, if the sentence isn't a well-formed, sentence in the target language press "no".
If the sentence is something that our team needs to jump on right away, it's a great fit for the "spam" button!

I hope this makes sense? I'll also make a note to make this clearer in documentation. I massively appreciate you flagging that this looks confusing. If you're ok with this, I'll also close this ticket.

**Comment by HarikalarKutusu** [comment]
Hey @jessicarose, thank you for the answer. To be clear:

This "Report" button has nothing to do with the one on the Speak / Listen versions, right?
As you know, the Report button on Speak & Listen does not do anything, except put a record in a separate TSV file in the release, but the sentences keep being shown for recording and listening.

If it acts similarly, if I say it is SPAM but two other people say it is OK, it will go into the text-corpus.
This will be NOT OK.

> As a general rule, if the sentence isn't a well-formed, sentence in the target language press "no".
In this case, the content of the pop-up should be changed.

> these will be flagged to the team
Does the team have knowledge of 100+ languages to look at the flagged sentences?
