### ISSUE TITLE
[BUG] Both ways of donating in CV not functional (android)

### ISSUE THREAD

**Issue by robovoice1** [common-voice/common-voice#4420]
**Describe the bug**
Please watch screenrecording 1+2

**To Reproduce**
1. Go to '...' https://commonvoice.mozilla.org/en
2. Click on '....'Log in and swipe down
3. Scroll down to '....' tap on donate
4. CV page reloads
Or
1. https://commonvoice.mozilla.org/en
2. log in
3. Tap on the 3 dots top left
4. Tap on the green donate button
5.  CV page reloads 

**Expected behavior**
The donation screen opens and is displayed

**Screenrecordings**

https://github.com/common-voice/common-voice/assets/92784377/771d5233-9956-4bbc-ba5d-9c72a6f97857

https://github.com/common-voice/common-voice/assets/92784377/e7820422-836c-45d0-8e13-7b8ebf726e3f

**Mobile (please complete the following information):**
 - OS: Android 14 GrapheneOS
 - Browser [e.g. chrome, safari] Vanadium
 - Version [e.g. 22] 123.0.6312.80

 **Additional Hardware (were you using headphones, an external speaker or an external microphone?):**
 - Type: Google Pixel
 - Model: 6 pro

**Additional context**

**Comment by jessicarose** [comment]
Thanks so much for flagging this, after some testing on my side and discussions with the engineers, we think that this bug is likely related to the way Vanadium handles iframes. As our donation flow is connected to a secure third party donation service that uses iframes to serve this modal, I fear that we're going to have to consider this bug for GrapheneOS + Vanadium users an edge case and close this ticket for now.

We have documented this in our internal docs for consideration and future roadmap planning around fundraising
