### ISSUE TITLE
[Enhancement] Adjust written sentence to spoken text

### ISSUE THREAD

**Issue by ichDaheim** [common-voice/common-voice#4527]
**Is your feature request related to a problem? Please describe.**
People skip a word or use another one instead. For example people say "the president" while text is "a president".

**Describe the solution you'd like**
In cases where the spoken text is just slightly different from the written sentence, beeing able to adjust the written text would save the recording for the corpus. As a security feature to prevent missuse of this functionality it then should be requeued for the "normal" validation cylce. Additionally showing the changes/history of the written text would further prevent missuse. After final validation only the validated text/audio pair should make it into the corpus.

**Describe alternatives you've considered**
"Lose" the sentence for the corpus by not validating it.

**Comment by HarikalarKutusu** [comment]
Sentences are hashed and that hash is used as an index for text-corpora. A single character change will make it another sentence. Users are presented with a sentence to record using that index, so I don't see a workflow where we can change the sentence, and obviously, we cannot change the audio. So, the wrong recording will (hopefully) go into "invalidated", and that sentence will be spoken correctly by one or multiple people, which will go into validated.

One usage of the sentence change is when a "wrong" sentence gets validated for recording (e.g. bad spelling/grammar). I think those should be manually invalidated by the community (leads / multiple people) and corrected ones should be re-inserted (this is what you mention as "lose the sentence"). This is important because people tend to correct those sentences while reading, so the transcript and audio will not match, worst thing for model training.

**Comment by ichDaheim** [comment]
Ah, okay. I wasn’t aware that the sentence is hashed.

**Comment by HarikalarKutusu** [comment]
@ichDaheim, actually it is just part of the reason. The process is like this:

1 sentence entry (+hash) => human sen. validation => 1-N recordings (some correct some not)
=>
valid recordings => human validation => validated
invalid recordings => human validation => invalidated

So you cannot change the source sentence, even if there was no hash, because there may be valid recordings...
That's the main reason.
