### ISSUE TITLE
[DOCS] clarify if GitHub can still be used for submitting sentences, and if the sentences can be accessed from the repository.

### ISSUE THREAD

**Issue by pereorga** [common-voice/common-voice#4550]
In https://github.com/common-voice/common-voice/pull/4377 @jessicarose states that "There's no longer any requirement to create a PR as part of a bulk sentences upload process.".
However, it is not clear if it is now required to use the web interface. (it could be, as per https://github.com/common-voice/common-voice/blob/main/docs/submitting-bulk-sentences.md, as GitHub or "pull request" is not mentioned in the document).

We plan to do bulk additions to the PCCD Catalan dataset (original PR: https://github.com/common-voice/common-voice/pull/3776). We would like to use GitHub if possible, because it is more transparent, and helps us getting track of the process via a standard, non-custom procedure.

Also, we would like to keep track of the submitted sentences, do you know if there is a way to access the submitted sentences in the repository?

Thanks

**Comment by HarikalarKutusu** [comment]
Let me try to answer as an active volunteer...

> We would like to use GitHub if possible

That functionality is commented out in the code and CV does not accept PR's for text-corpora anymore. I couldn't find it in a quick search, but a similar answer was answered in Matrix several months ago, stating that you should re-format the data and repost through the new interface. I'll edit this post if I find it.

> we would like to keep track of the submitted sentences, do you know if there is a way to access the submitted sentences in the repository

Sentences are not in the repository anymore, they go into the database, existent ones (under server/data/<lc>/*.txt) are from the old process.

With v17.0, the text-corpora became a part of dataset releases. There are two files `validated.sentences.tsv` and `unvalidated.sentences.tsv` which you can use. Some info is in the cv-dataset repo in [CHANGELOG.md](https://github.com/common-voice/cv-dataset/blob/main/CHANGELOG.md). But it is not fully informative for now, pls. see [this issue](https://github.com/common-voice/common-voice/issues/4428) for more detailed info.

AFAIK, the decision NOT to use GitHub PR's are based on scalability. Each time the server restarts, it was importing those sentences, and in time it became a very long process with added sentences.

A more detailed analysis of your text-corpus (for v18.0) can be found [here](https://analyzer.cv-toolbox.web.tr/examine/ca/18.0) under the TEXT CORPUS tab (also in Catalan). That does not include the extra data provided by the .tsv files, because I'm waiting for some stuff to be fixed.

**Comment by pereorga** [comment]
Thank you, @HarikalarKutusu! 

It's unfortunate we cannot contribute sentences via git. I'll try to use the new system next time.
