### ISSUE TITLE
Adding data collected by external source

### ISSUE THREAD

**Issue by Notnaton** [common-voice/common-voice#4606]
The Norwegian national library has voices and texts (some licensed CC-ZERO), available to download.
https://www.nb.no/sprakbanken/en/sprakbanken/

I thought I would just mention it as it could be useful for this project :)

**Comment by Notnaton** [comment]
Seems like Sweden also have some available: https://www.sprakbanken.se/sprakbanken-in-english/tools-and-resources

**Comment by jessicarose** [comment]
Thanks so much for thinking of the project! Right now, the Common Voice datasets can only ingest text or speech data that has been submitted via the Common Voice platforms. This is due to a mix of reasons which include data provenance, being able to track deletion requests, legal clearances and license compliance. This dataset looks amazing, I'll see if we can't highlight it to our community!
